on:
  push:

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Commit ID is ${{ github.sha }}
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: "{{ github.sha }}"
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_DV_CONTENTFUL_CLI }}
